vim9script

var config_dir = '~/.vim/config/'

var config_files = [
  'custom.vim',
  'fzf.vim',
  'mappings.vim',
  'settings.vim',
  'airline.vim',
  'fastfold.vim',
  'sneak.vim',
  'lsp.vim',
]

for config_file in config_files
  var full_path = expand(config_dir .. config_file)

  if filereadable(full_path)
    execute 'source ' .. full_path
  else
    echo 'Warning: Configuration file ' .. full_path .. ' not found'
  endif
endfor
